version = 1
SPDX-PackageName = "cdrive"
SPDX-PackageSupplier = "CDrive contributors"

[[annotations]]
path = ["img/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 CDrive contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
